# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'starterkit' do
  
  pod 'Firebase/Messaging'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

end

